name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # environment: production  # Uncomment after creating production environment in repo settings
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci --only=production

      - name: Build server
        working-directory: ./server
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - name: Prepare deployment package
        working-directory: ./server
        run: |
          # Create a minimal deployment package
          mkdir -p deploy
          cp -r dist/* deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp -r prisma deploy/
          # Create a .deployment file for Azure
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" > deploy/.deployment
          # Fix main entry point to point to dist folder
          sed -i 's/"main": "index.js"/"main": "dist\/index.js"/' deploy/package.json
          # List contents for debugging
          echo "Deployment package contents:"
          ls -la deploy/
          echo "Dist contents:"
          ls -la dist/

      - name: Deploy to Azure Web App - Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SMARTTASK-AI'
          slot-name: 'Production'
          package: ./server/deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3648A7C097704B079741BF447BA6A912 }}

      - name: Run Prisma migrations
        working-directory: ./server
        run: |
          echo "Running Prisma migrations..."
          npm run db:migrate:deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - name: Health check
        run: |
          echo "Performing health check..."
          # Add your production health check URL here
          # curl -f https://your-production-app.azurewebsites.net/health

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Successfully deployed to production"
          # Add notification logic (Slack, Discord, etc.)

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to production failed"
          # Add notification logic (Slack, Discord, etc.)
