name: Deploy Backend (ZIP + Publish Profile)

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read

concurrency:
  group: smarttask-ai-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Build server
        working-directory: server
        run: |
          set -e
          npm ci
          npm run build
          npm ci --omit=dev
          test -f dist/index.js || (echo "dist/index.js missing" && exit 1)

      - name: Verify runtime deps (express/cors)
        working-directory: server
        run: |
          node -e "try{require('express');require('cors');console.log('OK runtime deps');}catch(e){console.error('Missing runtime dependency (move it from devDependencies to dependencies):', e?.message||e); process.exit(1);}"

      - name: Verify dist artifacts exist
        run: |
          ls -lah server/dist || true
          ls -lah server/dist/routes || true
          node -e "const fs=require('fs');process.exit(fs.existsSync('server/dist/routes/clerkRoutes.js')?0:(console.error('missing dist/routes/clerkRoutes.js'),1));"

      - name: Create ZIP package (exclude Oryx & heavy frontend-only deps)
        run: |
          cd server
          zip -r ../backend-deployment.zip dist node_modules package.json package-lock.json \
            -x "oryx-manifest.toml" "node_modules/next/**" "node_modules/@next/**" "node_modules/typescript/**" "node_modules.tar.gz"
          cd ..
          ls -la backend-deployment.zip
          echo "ZIP size:" && du -h backend-deployment.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: backend-deployment.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-zip
          path: .
      - name: Verify downloaded package
        run: |
          ls -la
          test -f backend-deployment.zip || (echo "backend-deployment.zip missing after download" && exit 1)

      - name: Warm up App Service
        run: |
          for i in 1 2 3; do
            echo "Warmup attempt $i"
            curl -I --max-time 10 https://smarttask-ai-f6gzb6hgcrgngxhq.israelcentral-01.azurewebsites.net || true
            sleep $((5 * i))
          done

      - name: Deploy to Azure Web App (attempt 1)
        uses: azure/webapps-deploy@v3
        continue-on-error: true
        with:
          app-name: SMARTTASK-AI
          package: backend-deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3648A7C097704B079741BF447BA6A912 }}

      - name: Backoff before retry if needed
        if: failure()
        run: |
          echo "First deploy attempt failed; sleeping before retry..."
          sleep 25

      - name: Deploy to Azure Web App (attempt 2)
        if: failure()
        uses: azure/webapps-deploy@v3
        with:
          app-name: SMARTTASK-AI
          package: backend-deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3648A7C097704B079741BF447BA6A912 }}

      - name: Health check
        run: |
          sleep 30
          curl -f https://smarttask-ai-f6gzb6hgcrgngxhq.israelcentral-01.azurewebsites.net/health || exit 1
