name: Deploy Backend (ZIP + Publish Profile)

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read

concurrency:
  group: smarttask-ai-prod
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Build server
        working-directory: server
        run: |
          set -e
          npm ci
          npm run build
          npm ci --omit=dev
          test -f dist/index.js || (echo "dist/index.js missing" && exit 1)

      - name: Assemble deploy folder
        run: |
          rm -rf server/deploy
          mkdir -p server/deploy
          cp -r server/dist server/deploy/dist
          cp -r server/node_modules server/deploy/node_modules
          cp server/package.json server/deploy/package.json
          cp server/package-lock.json server/deploy/package-lock.json
          if [ -d "server/prisma" ]; then cp -r server/prisma server/deploy/prisma; fi
          # IMPORTANT: do NOT copy .deployment or oryx-manifest.toml

      - name: Create ZIP package
        run: |
          cd server/deploy
          zip -r ../backend-deployment.zip .
          cd ..
          ls -la backend-deployment.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: server/backend-deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-zip

      - name: Deploy to Azure Web App (Publish Profile only)
        uses: azure/webapps-deploy@v3
        with:
          app-name: SMARTTASK-AI
          package: backend-deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3648A7C097704B079741BF447BA6A912 }}

      - name: Health check
        run: |
          sleep 30
          curl -f https://smarttask-ai-f6gzb6hgcrgngxhq.israelcentral-01.azurewebsites.net/health || exit 1
