name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read

# Prevent parallel deployments
concurrency:
  group: backend-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Build application
        working-directory: server
        run: npm run build

      - name: Install production dependencies
        working-directory: server
        run: npm ci --omit=dev

      - name: Create deployment package
        working-directory: server
        run: |
          # Create a simple startup script
          cat > startup.sh << 'EOF'
          #!/bin/bash
          cd "$(dirname "$0")"
          echo "Starting application..."
          node dist/index.js
          EOF
          chmod +x startup.sh
          
          # Create deployment ZIP
          zip -r ../deployment.zip . -x "node_modules/.cache/*" "*.log" ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: SMARTTASK-AI
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3648A7C097704B079741BF447BA6A912 }}
          package: server/deployment.zip

      - name: Wait for deployment
        run: sleep 30

      - name: Health check
        run: |
          echo "Testing application health..."
          for i in {1..5}; do
            echo "Attempt $i/5"
            if curl -f -s --max-time 10 https://smarttask-ai-f6gzb6hgcrgngxhq.israelcentral-01.azurewebsites.net/health; then
              echo "✅ Application is healthy"
              exit 0
            else
              echo "⚠️ Health check failed, retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "❌ Health check failed after 5 attempts"
          exit 1
